targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/gen/{{}}.g.dart'
      mobx_codegen|mobx_generator:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/gen/{{}}.g.dart'
      chopper_generator|chopper_generator:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/gen/{{}}.chopper.dart'